import { Header } from "@/components/header"

import type { Metadata } from "next"

export const metadata: Metadata = { title: "Privacy Policy | Lotus Wellness", description: "How Lotus Wellness handles booking and enquiry information.", alternates: { canonical: "/privacy" } }

export default function PrivacyPage() {
  return <><Header /><main className="min-h-screen bg-background px-5 py-16 text-foreground sm:px-8"><article className="mx-auto max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-accent">Lotus Wellness</p><h1 className="mt-4 font-serif text-5xl font-light">Privacy Policy</h1><p className="mt-6 leading-7 text-muted-foreground">This policy explains how Lotus Wellness uses information submitted through this website for mobile wellness services in Ho Chi Minh City.</p><h2 className="mt-10 font-serif text-3xl">Information we collect</h2><p className="mt-4 leading-7 text-muted-foreground">We may collect your name, email address, phone number, service preferences, appointment details, and location information when you request a booking or contact our team.</p><h2 className="mt-10 font-serif text-3xl">How we use information</h2><p className="mt-4 leading-7 text-muted-foreground">We use this information to respond to enquiries, confirm appointments, coordinate therapists, process requested services, send service updates, and protect the security of our operations. We do not sell personal information.</p><h2 className="mt-10 font-serif text-3xl">Retention and requests</h2><p className="mt-4 leading-7 text-muted-foreground">We retain information only for as long as reasonably needed for bookings, customer support, accounting, safety, or legal obligations. You may ask us to access, correct, or delete your information, subject to applicable requirements.</p><h2 className="mt-10 font-serif text-3xl">Contact</h2><p className="mt-4 leading-7 text-muted-foreground">For privacy questions or requests, please use the contact options on this website. Lotus Wellness will update this policy when its services or legal obligations change.</p></article></main></>
}
