import { Header } from "@/components/header"

import type { Metadata } from "next"

export const metadata: Metadata = { title: "Terms of Service | Lotus Wellness", description: "Terms for booking Lotus Wellness mobile massage services.", alternates: { canonical: "/terms" } }

export default function TermsPage() {
  return <><Header /><main className="min-h-screen bg-background px-5 py-16 text-foreground sm:px-8"><article className="mx-auto max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-accent">Lotus Wellness</p><h1 className="mt-4 font-serif text-5xl font-light">Terms of Service</h1><p className="mt-6 leading-7 text-muted-foreground">These terms apply to requests and bookings for Lotus Wellness mobile wellness services in Ho Chi Minh City.</p><h2 className="mt-10 font-serif text-3xl">Bookings</h2><p className="mt-4 leading-7 text-muted-foreground">A booking request is not confirmed until Lotus Wellness confirms the service, therapist, time, location, and price. Please provide accurate contact and location details so our team can coordinate safely.</p><h2 className="mt-10 font-serif text-3xl">Changes and cancellations</h2><p className="mt-4 leading-7 text-muted-foreground">Please contact us as early as possible if you need to change or cancel an appointment. Any applicable cancellation, waiting, travel, or payment terms will be communicated before confirmation.</p><h2 className="mt-10 font-serif text-3xl">Service boundaries</h2><p className="mt-4 leading-7 text-muted-foreground">Our services are for wellness and relaxation and are not medical diagnosis or emergency care. Tell your therapist about relevant health considerations and stop a session if you feel unwell. Lotus Wellness may decline a request where safety, consent, or respectful conduct cannot be maintained.</p><h2 className="mt-10 font-serif text-3xl">Contact</h2><p className="mt-4 leading-7 text-muted-foreground">Questions about these terms should be sent through the contact options on this website. These terms may be updated when our services or legal requirements change.</p></article></main></>
}
